swiftmailer:
  transport:  smtp
  username: contact@neonetconsulting.com
  password: 8Qe6c7XM6c
  host: ssl0.ovh.net
  port: 465
  encryption: ssl
  auth-mode:  login
  spool: { type: 'memory' }
  stream_options:
    ssl:
      allow_self_signed: true
      verify_peer: false
      verify_peer_name: false